// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCharacters() {
  return window['go']['main']['App']['GetAllCharacters']();
}

export function GetServantDetail(arg1) {
  return window['go']['main']['App']['GetServantDetail'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
