// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllCharacters():Promise<Array<main.Character>>;

export function GetServantDetail(arg1:string):Promise<main.ServantDetail>;

export function Greet(arg1:string):Promise<string>;
